name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t my_app:latest .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          docker run --rm my_app pytest tests/
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: ./deployment_scripts/deploy.sh
